[looper]
manager=["go"]
gorepo="github.com/nathany/looper"

[fzf]
manager=["go"]
gorepo="github.com/junegunn/fzf"

[neovim-godev]
manager=["phony"]
dependency=["neovim", "go"]
tasks=["nvim -c GoInstallBinaries -c q"]

[neovim]
manager=["brew"]
dependency=["python-neovim-plugin"]
brewtap="neovim/neovim"

[python-neovim-plugin]
manager=["pip"]
pipname="neovim"

[go]
manager=["brew"]

[git]
manager=["brew"]

[docker]
manager=["brew"]

[tmux]
manager=["brew"]

[openssl]
manager=["brew"]

[readline]
manager=["brew"]


[gh]
brewname="github/gh/gh"
manager=["brew"]

[terraform]
manager=["brew"]


# GUI APPs
[docker-gui]
manager=["brewcask"]
brewname="docker"

[iterm2]
manager=["brewcask"]

[clipy]
manager=["brewcask"]

[google-chrome]
manager=["brewcask"]

[slack]
manager=["brewcask"]

[1password]
manager=["brewcask"]

[notion]
manager=["brewcask"]

[macdown]
manager=["brewcask"]

[microsoft-word]
manager=["brewcask"]

[microsoft-powerpoint]
manager=["brewcask"]

[microsoft-excel]
manager=["brewcask"]
